LIB_DIR = ../../lib
STUBS = Logger StubLogger
INCLUDES = $(LIB_DIR)/Angle/ $(LIB_DIR)/Utility/ $(LIB_DIR)/Position/ $(LIB_DIR)/Globe ../Boat ../Timer
SOURCES = $(LIB_DIR)/Angle/Angle.cpp $(LIB_DIR)/Globe/Globe.cpp ../Boat/Boat.cpp ../Timer/Timer.cpp

include $(LIB_DIR)/libcommon
