LIB_DIR = ../../lib
STUBS = Logger StubLogger
INCLUDES = $(LIB_DIR)/Angle/ $(LIB_DIR)/Utility/ $(LIB_DIR)/Position/ $(LIB_DIR)/Globe ../Boat ../Timer ../LiftDrag
SOURCES = $(LIB_DIR)/Angle/Angle.cpp $(LIB_DIR)/Globe/Globe.cpp ../Boat/Boat.cpp ../Timer/Timer.cpp ../LiftDrag/LiftDrag.cpp

include $(LIB_DIR)/libcommon
