LIBS = Utility Angle CompassWire WindSensorWire MServo SDLogger Rudder
# For libs that require all files, not just the standard .cpp and .h
LIBS_ALL = Compass WindSensor Logger Position PololuMaestro

include ../lib/common
