STUBS = StubLogger Logger
INCLUDES = . ../../lib/Position/ ../../lib/Globe/ ../../lib/Angle/ ../../lib/Utility/ ../LiftDrag/ ../../lib/Sail/ ../MServo/ ../Arduino/
SOURCES = ../../lib/Globe/Globe.cpp ../../lib/Angle/Angle.cpp ../LiftDrag/LiftDrag.cpp ../../lib/Sail/Sail.cpp ../MServo/MServo.cpp
LIST_TEST_OPTS = --gtest_list_tests
TEST_ONLY_TEST_OPTS = --gtest_filter=BoatTest.Sail_force_should_vary_with_wind_maximum_on_broad_reach
include ../../lib/libcommon
