STUBS = StubLogger Logger
INCLUDES = ../../lib/Position/ ../../lib/Globe/ ../../lib/Angle/ ../../lib/Utility/
SOURCES = ../../lib/Globe/Globe.cpp ../../lib/Angle/Angle.cpp

include ../../lib/libcommon
