STUBS = StubLogger Logger
INCLUDES = ../../lib/Position/ ../../lib/Globe/ ../../lib/Angle/ ../../lib/Utility/
SOURCES = ../../lib/Globe/Globe.cpp ../../lib/Angle/Angle.cpp
LIST_TEST_OPTS = --gtest_list_tests
TEST_ONLY_TEST_OPTS = --gtest_filter=BoatTest.Should_move_in_initial_direction_about_2m
include ../../lib/libcommon
