STUBS = Tacker Gps Logger WindSensor Compass StubLogger Arduino
INCLUDES = ../Angle/ ../Utility/ ../Waypoint/ ../Position/ ../Globe/
SOURCES = ../Angle/Angle.cpp ../Globe/Globe.cpp

include ../libcommon
