LIBS = Utility Angle WindSensor Compass SerialLogger DisplayLogger Rudder Sail Gps
# For libs that require non-standard lib files, not just the standard .cpp and .h
LIBS_ALL = Adafruit_GPS_Library Adafruit_SSD1306 Adafruit_GFX Logger Position

include ../lib/common
