LIBS = Utility Angle Compass WindSensor Gps MServo SDLogger Timer
# Rudder
# For libs that require all files, not just the standard .cpp and .h
LIBS_ALL = PololuMaestro Position Logger Adafruit_GPS_Library

include ../lib/common
