STUBS = Compass Rudder Sail Timer WindSensor Logger StubLogger Gps RotaryPID Arduino SatComm
INCLUDES = ../Angle/ ../Utility/ ../Position/ ../Windrange/ ../IHelm
SOURCES = ../Angle/Angle.cpp

include ../libcommon
