LIBS = Angle Captain SDLogger Globe Gps Helm Navigator Rudder RotaryPID Sail Tacker Timer Utility Switches MServo I2C Compass WindSensor Battery
# For libs that require all files or only an .h file, not just the standard .cpp and .h
LIBS_ALL = SD Adafruit_GPS_Library Logger Position Waypoint Routes Windrange PololuMaestro IHelm

include ../lib/common
