LIBS = Angle Helm Rudder Sail Timer Utility MServo Switches RotaryPID
# For libs that require all files or only an .h file, not just the standard .cpp and .h
LIBS_ALL = Logger Position Windrange PololuMaestro

include ../lib/common
