LIBS = Angle Compass SDLogger Helm Rudder Sail Tacker Timer Utility WindSensor RotaryPID MServo
# For libs that require all files or only an .h file, not just the standard .cpp and .h
LIBS_ALL = Logger Position Waypoint Routes Windrange PololuMaestro

include ../lib/common
